[workspace]
projects = [
    "test",
    "docs",
    "lib/BayesDensityCore",
    "lib/BayesDensityBSplineMixture",
    "lib/BayesDensityHistSmoother",
    "lib/BayesDensityPitmanYorMixture",
    "lib/BayesDensity"
]