[workspace]
projects = ["test", "docs", "lib/BayesDensityCore", "lib/BayesDensityBSplineMixture", "lib/BayesDensityHistSmoother", "lib/BayesDensityPitmanYorMixture", "lib/BayesDensityFiniteGaussianMixture", "lib/BayesDensity"]

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
