[deps]
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
BayesDensity = "4cc3c169-7268-405b-84ce-cc9eca2341c2"
BayesDensityBSplineMixture = "dc1a60f9-7a32-4f65-8b9e-ee7db92abd95"
BayesDensityCore = "93712312-7690-42d2-80ab-295e38cb0be8"
BayesDensityFiniteGaussianMixture = "588bb9d7-6d85-4df3-a9ca-7b66fb5e4296"
BayesDensityHistSmoother = "4ec5b509-5e49-418c-a128-3e7a20b6d93e"
BayesDensityPitmanYorMixture = "9da0b0c8-0459-4567-a5a4-3605fb8f6d57"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"